export const ADMIN_NAME: string = 'GUVANCH'
export const ADMIN_PASSWORD: string = 'GUVANCH99'
export const ALL_PRODUCTS: string = '/all-products'
export const PRICE: string = 'price'
export const ORDERS: string = '/orders'
export const FILE_TYPE: string = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
export const TODAY: string = 'Today'
export const LAST_WEEK: string = 'Last Week'
export const TWO_WEEKS: string = 'Two Weeks'
export const MONTH: string = '1 Month'
export const TWO_MONTH: string = '2 Month'
export const EMPTY: string = ' '
export const PERIOD: string = 'Period'
export const THREE=3
export const NEXT_ID = 2
export const EXPECTED_INCOME = 500
export const HUNDRED_PERCENT = 100
export const FIRST_SEGMENT_OFF_SET = 25
export const LIMIT_ITEMS = 4
export const FIVE_MB = 5242880
