export const ADMIN_NAME:string = 'GUVANCH'
export const ADMIN_PASSWORD:string  = 'GUVANCH99'
export const ALL_PRODUCTS:string  = '/all-products'
export const PRICE:string  = 'price'
export const ORDERS:string  = '/orders'
export const NEXT_ID:number  = 2
export const EXPECTED_INCOME:number = 500
export const HUNDRED_PERCENT:number = 100
export const FIRST_SEGMENT_OFF_SET:number = 25
export const LIMIT_ITEMS:number = 4
export const FIVE_MB:number = 5242880
export const FILE_TYPE:string='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
export const TODAY:string='Today'
export const LAST_WEEK:string='Last Week'
export const TWO_WEEKS:string='Two Weeks'
export const MONTH:string='1 Month'
export const TWO_MONTH:string='2 Month'
export const EMPTY:string=' '
export const PERIOD:string='Period'